# Benchmark the reliability solvers on the problems

In this example, we show how to run all the methods on all the problems and get the computed probability.

In [1]:
import openturns as ot
import numpy as np
import otbenchmark as otb
import pandas as pd
import csv
from tqdm import tqdm
from IPython.display import display, HTML

In [2]:
ot.Log.Show(ot.Log.NONE)

We import the list of reliability problems.

In [3]:
benchmarkProblemList = otb.ReliabilityBenchmarkProblemList()
numberOfProblems = len(benchmarkProblemList)
numberOfProblems

26

For each problem in the benchmark, print the problem name and the exact failure probability.

In [4]:
for i in range(numberOfProblems):
    problem = benchmarkProblemList[i]
    name = problem.getName()
    pf = problem.getProbability()
    print("#", i, " : ", name, ", exact PF : ", pf)

# 0  :  RP8 , exact PF :  0.0007897927545597451
# 1  :  RP14 , exact PF :  0.00752
# 2  :  RP22 , exact PF :  0.00416
# 3  :  RP24 , exact PF :  0.00286
# 4  :  RP25 , exact PF :  6.14e-06
# 5  :  RP28 , exact PF :  1.4532945550025393e-07
# 6  :  RP31 , exact PF :  0.00018
# 7  :  RP33 , exact PF :  0.00257
# 8  :  RP35 , exact PF :  0.00354
# 9  :  RP38 , exact PF :  0.0081
# 10  :  RP53 , exact PF :  0.0313
# 11  :  RP55 , exact PF :  0.5600144282863704
# 12  :  RP54 , exact PF :  0.000998
# 13  :  RP57 , exact PF :  0.0284
# 14  :  RP75 , exact PF :  0.0107
# 15  :  RP89 , exact PF :  0.00543
# 16  :  RP107 , exact PF :  2.92e-07
# 17  :  RP110 , exact PF :  3.19e-05
# 18  :  RP111 , exact PF :  7.65e-07
# 19  :  RP63 , exact PF :  0.000379
# 20  :  RP91 , exact PF :  0.000697
# 21  :  RP60 , exact PF :  0.0456
# 22  :  RP77 , exact PF :  2.87e-07
# 23  :  Four-branch serial system , exact PF :  0.002185961454913241
# 24  :  R-S , exact PF :  0.07864960352514257
# 25  :  Axial stressed beam , exact PF :  0.02919819462483095

## Run several algorithms on a single problem

We want to run several algorithms on a single problem. We set the parameters of the algorithms and run them on a single problem.

In [5]:
maximumEvaluationNumber = 1000
maximumAbsoluteError = 1.0e-3
maximumRelativeError = 1.0e-3
maximumResidualError = 1.0e-3
maximumConstraintError = 1.0e-3
nearestPointAlgorithm = ot.AbdoRackwitz()
nearestPointAlgorithm.setMaximumCallsNumber(maximumEvaluationNumber)
nearestPointAlgorithm.setMaximumAbsoluteError(maximumAbsoluteError)
nearestPointAlgorithm.setMaximumRelativeError(maximumRelativeError)
nearestPointAlgorithm.setMaximumResidualError(maximumResidualError)
nearestPointAlgorithm.setMaximumConstraintError(maximumConstraintError)

In [6]:
i = 3
problem = benchmarkProblemList[i]
metaAlgorithm = otb.ReliabilityBenchmarkMetaAlgorithm(problem)

We try the FORM algorithm.

In [7]:
benchmarkFORM = metaAlgorithm.runFORM(nearestPointAlgorithm)
s1 = benchmarkFORM.summary()
print(s1)

computedProbability = 0.006209245091320793
exactProbability = 0.00286
absoluteError = 0.003349245091320793
numberOfCorrectDigits = 0.0
numberOfFunctionEvaluations = 5
numberOfDigitsPerEvaluation = 0.0

Then the SORM algorithm.

In [8]:
benchmarkSORM = metaAlgorithm.runSORM(nearestPointAlgorithm)
s2 = benchmarkSORM.summary()
print(s2)

computedProbability = 0.006209245091320793
exactProbability = 0.00286
absoluteError = 0.003349245091320793
numberOfCorrectDigits = 0.0
numberOfFunctionEvaluations = 5
numberOfDigitsPerEvaluation = 0.0

In [9]:
benchmarkMC = metaAlgorithm.runMonteCarlo(
    maximumOuterSampling=1000000, coefficientOfVariation=0.1, blockSize=1,
)
s3 = benchmarkMC.summary()
print(s3)

computedProbability = 0.002858694719990857
exactProbability = 0.00286
absoluteError = 1.3052800091430984e-06
numberOfCorrectDigits = 3.340662346449938
numberOfFunctionEvaluations = 34981
numberOfDigitsPerEvaluation = 9.549933811068688e-05

In [10]:
benchmarkFORMIS = metaAlgorithm.runFORMImportanceSampling(
    nearestPointAlgorithm,
    maximumOuterSampling=1000,
    coefficientOfVariation=0.1,
    blockSize=1,
)
s4 = benchmarkFORMIS.summary()
print(s4)

computedProbability = 0.0028912458245778103
exactProbability = 0.00286
absoluteError = 3.124582457781017e-05
numberOfCorrectDigits = 1.9615740429360635
numberOfFunctionEvaluations = 601
numberOfDigitsPerEvaluation = 0.003263850321025064

In [11]:
benchmarkSS = metaAlgorithm.runSubsetSampling(
    maximumOuterSampling=5000, coefficientOfVariation=0.1, blockSize=1,
)
s5 = benchmarkSS.summary()
print(s5)

computedProbability = 0.002817999999999997
exactProbability = 0.00286
absoluteError = 4.200000000000297e-05
numberOfCorrectDigits = 1.8331167427311117
numberOfFunctionEvaluations = 15000
numberOfDigitsPerEvaluation = 0.0001222077828487408

## Run all algorithms on all problems and produce a single result table

For several algorithms and all the reliability problems, we want to estimate the failure probability and compare them.

We create a list of problem names.

In [12]:
problem_names = []
for i in range(numberOfProblems):
    problem = benchmarkProblemList[i]
    name = problem.getName()
    problem_names.append(name)

In [13]:
metrics = [
    "Exact",
    "FORM",
    "SORM",
    "Monte Carlo",
    "FORM-IS",
    "Subset",
]
results = np.zeros((numberOfProblems, len(metrics)))
maximumOuterSampling = 10 ** 2
blockSize = 10 ** 2
coefficientOfVariation = 0.0

for i in tqdm(range(numberOfProblems)):
    problem = benchmarkProblemList[i]
    results[i][0] = problem.getProbability()
    metaAlgorithm = otb.ReliabilityBenchmarkMetaAlgorithm(problem)
    benchmarkResult = metaAlgorithm.runFORM(nearestPointAlgorithm)
    results[i][1] = benchmarkResult.computedProbability
    benchmarkResult = metaAlgorithm.runSORM(nearestPointAlgorithm)
    results[i][2] = benchmarkResult.computedProbability
    benchmarkResult = metaAlgorithm.runMonteCarlo(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[i][3] = benchmarkResult.computedProbability
    benchmarkResult = metaAlgorithm.runFORMImportanceSampling(
        nearestPointAlgorithm,
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[i][4] = benchmarkResult.computedProbability
    benchmarkResult = metaAlgorithm.runSubsetSampling(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[i][5] = benchmarkResult.computedProbability

df = pd.DataFrame(results, index=problem_names, columns=metrics)
df

100%|████████████████████████████████████████████████████████| 26/26 [00:33<00:00,  1.29s/it]

,Exact,FORM,SORM,Monte Carlo,FORM-IS,Subset
RP8,7.897928e-04,6.598878e-04,7.838036e-04,0.0004,7.996083e-04,9.154000e-04
RP14,7.520000e-03,7.003011e-04,6.995436e-04,0.0010,7.735961e-04,7.201000e-04
RP22,4.160000e-03,6.209672e-03,4.390902e-03,0.0043,4.313709e-03,3.899000e-03
RP24,2.860000e-03,6.209245e-03,6.209245e-03,0.0030,2.816315e-03,2.518000e-03
RP25,6.140000e-06,6.349319e-03,6.349319e-03,0.0001,4.476962e-05,3.874122e-05
RP28,1.453295e-07,2.850470e-08,0.000000e+00,0.0000,1.263642e-07,1.319034e-07
RP31,1.800000e-04,2.275013e-02,2.275013e-02,0.0033,2.993455e-03,2.940000e-03
RP33,2.570000e-03,1.349898e-03,1.349898e-03,0.0032,2.511609e-03,2.489508e-03
RP35,3.540000e-03,1.349898e-03,2.134376e-03,0.0037,2.331039e-03,3.964000e-03
RP38,8.100000e-03,7.902212e-03,8.029356e-03,0.0064,8.154653e-03,8.229000e-03
RP53,3.130000e-02,1.180398e-01,2.986164e-02,0.0299,3.055716e-02,3.130000e-02
RP55,5.600144e-01,4.992557e-01,7.899011e-06,0.5672,5.580282e-01,5.619000e-01
RP54,9.980000e-04,5.555704e-02,3.554811e-03,0.0012,9.904772e-04,9.530000e-04
RP57,2.840000e-02,4.866078e-02,4.866078e-02,0.0303,1.464540e-02,2.864000e-02
RP75,1.070000e-02,0.000000e+00,0.000000e+00,0.0102,0.000000e+00,9.909000e-03
RP89,5.430000e-03,2.008594e-09,2.008594e-09,0.0042,3.990898e-05,5.657000e-03
RP107,2.920000e-07,2.866516e-07,2.866516e-07,0.0000,2.959485e-07,2.720551e-07
RP110,3.190000e-05,3.167124e-05,3.167124e-05,0.0000,3.270339e-05,2.137128e-06
RP111,7.650000e-07,0.000000e+00,0.000000e+00,0.0000,0.000000e+00,9.275110e-07
RP63,3.790000e-04,9.999966e-01,0.000000e+00,0.0003,0.000000e+00,3.735000e-04
RP91,6.970000e-04,6.994296e-04,7.011592e-04,0.0008,6.726035e-04,7.972000e-04
RP60,4.560000e-02,4.483968e-02,4.483968e-02,0.0488,4.514307e-02,4.478000e-02
RP77,2.870000e-07,6.276208e-03,0.000000e+00,0.0000,2.275994e-07,1.871127e-07
Four-branch serial system,2.185961e-03,0.000000e+00,0.000000e+00,0.0023,0.000000e+00,2.005000e-03
R-S,7.864960e-02,7.864960e-02,7.864960e-02,0.0751,7.964098e-02,7.842000e-02
Axial stressed beam,2.919819e-02,2.998280e-02,2.933256e-02,0.0309,3.031439e-02,2.997000e-02

In [14]:
df.to_csv("reliability_benchmark_table-output.csv")

## Run several algorithms on all problems and get detailed statistics

Run several algorithms on all reliability benchmark problems: print statistics on each problem.

In [15]:
def FormatRow(benchmarkResult):
    """Format a single row of the benchmark table"""
    result = [
        benchmarkResult.exactProbability,
        benchmarkResult.computedProbability,
        benchmarkResult.absoluteError,
        benchmarkResult.numberOfCorrectDigits,
        benchmarkResult.numberOfFunctionEvaluations,
        benchmarkResult.numberOfDigitsPerEvaluation,
    ]
    return result

In [16]:
method_names = ["Monte-Carlo", "FORM", "SORM", "FORM-IS", "SUBSET"]

maximumOuterSampling = 10 ** 2
blockSize = 10 ** 2
coefficientOfVariation = 0.0

for i in range(numberOfProblems):
    problem = benchmarkProblemList[i]
    name = problem_names[i]
    exact_pf_name = "%10s" % ("Exact PF " + name[0:10])
    metrics = [
        exact_pf_name,
        "Estimated PF",
        "Absolute Error",
        "Correct Digits",
        "Function Calls",
        "Digits / Evaluation",
    ]
    results = np.zeros((len(method_names), len(metrics)))
    metaAlgorithm = otb.ReliabilityBenchmarkMetaAlgorithm(problem)
    # Monte-Carlo
    benchmarkResult = metaAlgorithm.runMonteCarlo(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[0, :] = FormatRow(benchmarkResult)
    # FORM
    benchmarkResult = metaAlgorithm.runFORM(nearestPointAlgorithm)
    results[1, :] = FormatRow(benchmarkResult)
    # SORM
    benchmarkResult = metaAlgorithm.runSORM(nearestPointAlgorithm)
    results[2, :] = FormatRow(benchmarkResult)
    # FORM-IS
    benchmarkResult = metaAlgorithm.runFORMImportanceSampling(
        nearestPointAlgorithm,
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[3, :] = FormatRow(benchmarkResult)
    # Subset
    benchmarkResult = metaAlgorithm.runSubsetSampling(
        maximumOuterSampling=maximumOuterSampling,
        coefficientOfVariation=coefficientOfVariation,
        blockSize=blockSize,
    )
    results[4, :] = FormatRow(benchmarkResult)
    # Gather statistics and print them
    df = pd.DataFrame(results, index=method_names, columns=metrics,)
    # Format the columns for readability
    s = df.style.format(
        {
            exact_pf_name: lambda x: "{:.3e}".format(x),
            "Estimated PF": lambda x: "{:.3e}".format(x),
            "Absolute Error": lambda x: "{:.3e}".format(x),
            "Correct Digits": lambda x: "{:.1f}".format(x),
            "Function Calls": lambda x: "{:d}".format(int(x)),
            "Estimated PF": lambda x: "{:.2e}".format(x),
            "Digits / Evaluation": lambda x: "{:.1f}".format(x),
        }
    )
    display(s)